/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      'xs':  '375px',
      'sm':  '640px',
      'md':  '768px',
      'lg':  '1024px',
      'xl':  '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        maroon:          '#800000',
        mustard:         '#FFDB58',
        gold:            '#D4AF37',
        cream:           '#FFFDD0',
        saffron:         '#FF8C00',
        amber:           '#E8B84B',
        copper:          '#B87333',
        ivory:           '#FFFFF0',
        'gold-light':    '#F5D78E',
        'gold-deep':     '#b8952e',
        'maroon-light':  '#A52828',
        'maroon-dark':   '#5C0000',
        'maroon-deep':   '#3d0000',
        'teal-jewel':    '#006b75',
        'emerald-deep':  '#0c5531',
      },
      fontFamily: {
        serif:    ['"Cormorant Garamond"', 'Georgia', 'serif'],
        sans:     ['"Plus Jakarta Sans"', 'sans-serif'],
        kannada:  ['"Noto Sans Kannada"', '"Noto Serif Kannada"', 'sans-serif'],
        display:  ['"Cinzel Decorative"', '"Cormorant Garamond"', 'serif'],
        mono:     ['"JetBrains Mono"', 'monospace'],
      },
      animation: {
        'fade-in':      'fadeIn 0.8s ease-out forwards',
        'fade-in-up':   'fadeInUp 0.9s ease-out forwards',
        'float':        'float 4s ease-in-out infinite',
        'pulse-gold':   'pulseGold 2s ease-in-out infinite',
        'spin-slow':    'spin 12s linear infinite',
        'shimmer':      'shimmer 3s ease-in-out infinite',
        'glow-breathe': 'glowBreathe 3s ease-in-out infinite',
        'slide-up':     'slideUp 0.6s ease-out forwards',
        'reveal':       'reveal 1s ease-out forwards',
      },
      keyframes: {
        fadeIn:       { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInUp:     { '0%': { opacity: '0', transform: 'translateY(30px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        float:        { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-12px)' } },
        pulseGold:    { '0%,100%': { boxShadow: '0 0 0 0 rgba(212,175,55,0.4)' }, '50%': { boxShadow: '0 0 0 14px rgba(212,175,55,0)' } },
        shimmer:      { '0%': { backgroundPosition: '-200% center' }, '100%': { backgroundPosition: '200% center' } },
        glowBreathe:  { '0%,100%': { filter: 'drop-shadow(0 0 8px rgba(212,175,55,0.3))' }, '50%': { filter: 'drop-shadow(0 0 24px rgba(212,175,55,0.7))' } },
        slideUp:      { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        reveal:       { '0%': { opacity: '0', transform: 'translateY(40px) scale(0.97)' }, '100%': { opacity: '1', transform: 'translateY(0) scale(1)' } },
      },
      boxShadow: {
        'gold':       '0 4px 24px 0 rgba(212,175,55,0.25)',
        'gold-lg':    '0 8px 48px 0 rgba(212,175,55,0.35)',
        'gold-glow':  '0 0 40px 0 rgba(212,175,55,0.4)',
        'maroon':     '0 4px 24px 0 rgba(128,0,0,0.20)',
        'saffron':    '0 4px 24px 0 rgba(255,140,0,0.25)',
        'inset-gold': 'inset 0 0 60px 0 rgba(212,175,55,0.08)',
      },
      backgroundImage: {
        'gold-metallic': 'linear-gradient(135deg, #c9991e 0%, #FFDB58 25%, #fff4b0 50%, #D4AF37 75%, #b8952e 100%)',
        'gold-shimmer':  'linear-gradient(90deg, transparent 0%, rgba(255,219,88,0.4) 50%, transparent 100%)',
      },
      backdropBlur: {
        'xs': '2px',
      },
    },
  },
  plugins: [],
}
